### ISSUE TITLE
Please don't give up!

### ISSUE THREAD

**Issue by Bendor** [socketio/socket.io-client-java#570]
Thank you very much for implementing socket.io on android! I sure this project is important for a large number of applications!
However, recent changes in the code were made more than 2 years ago(

I understand that it is difficult to find time for everything, but I ask you don't give up this project!

**Comment by Fi5t** [comment]
Hey guys, we really miss without updates....

**Comment by guftall** [comment]
@Bendor @Fi5t
Of course you can update last changes date to now, just spend some time and make some useful PR. :)

**Comment by haruntuncay** [comment]
I could actively maintain a fork if interest is high. Please let me know if you are depending on this library and would like an active fork.

**Comment by nkzawa** [comment]
Sorry for the inactivity. Unfortunately, I have no time working in the library but I can add you as collaborators if you're interested.

**Comment by haruntuncay** [comment]
Yes, I am interested to be a collaborator on this library.

**Comment by rauchg** [comment]
@haruntuncay can you tell us more about yourself? We are super interested in welcoming new contributors, but not super motivated due to the lack of profile picture and other details on your profile.

Apologize for the odd question, but we want to act with caution to not let the community down. Thank you!

**Comment by haruntuncay** [comment]
Hello Guillermo,

I would like to thank you for getting in contact with me.
Briefly about myself, I am currently 3rd grade Computer Engineering student from Turkey who is really into Java, and recently I have been trying to get active on open source projects, which I assume you have noticed, since you talked to @TooTallNate<https://github.com/TooTallNate>. Sorry that I couldn't provide you with any info earlier because apparently we are on a really different time-zones, your messages are delivered to me in 6 Am. By the way, I will make sure to update my GitHub profile 😄.

Also, I have received a collaboration invite from @TooTallNate<https://github.com/TooTallNate>, which I am really happy about, but just surprised since I was initially chatting about the socket.io-client-java<https://github.com/socketio/socket.io-client-java> library. If you are still looking for a collaborator for socket.io java, I still would like to offer my help, that is of course if I seem eligible.

Sincerely,
Harun Tuncay

________________________________

**Comment by WyattMufson** [comment]
@rauchg @nkzawa I would also be interested in contributing and maintaining this repo. I've been using socket.io in node and Swift for the last few months and am going to be beginning android development with it in the next few weeks. Happy to provide any more details you might need.

**Comment by KushtrimPacaj** [comment]
@nkzawa 
I'm using this project, so I'm up for contributing more on it. But most of the issues reported really seem like user mistakes.  If you guys could find the time to clear some of the useless reports and find ones with actual bugs, I can find some time to help out with the fixes.

As for the maintainers, it'd be good to at least check the PRs that have been made.  Seeing many open PRs that fix_stuff/add_features not even looked at, will for sure turn away any prospecting contributors :P

**Comment by DivineThreepwood** [comment]
@nkzawa is there any reason why @haruntuncay is still not added as contributor?

**Comment by haruntuncay** [comment]
@DivineThreepwood, I didn't contributed anything to this project, but I am working on [Java-Websocket](https://github.com/TooTallNate/Java-WebSocket). I believe maintainers of the project don't seem to have the time to review contributions currently.

**Comment by DivineThreepwood** [comment]
@haruntuncay thanks for the feedback. At least you offered your support for this lib in March:

> If you are still looking for a collaborator for socket.io java, I still would like to offer my help 

I thought your offer would get more attention especially because the current maintainer seems to be to busy to still maintain this project. 

> I am working on Java-Websocket

that's not a suitable alternative for this lib, right? At least its seems not to be compatible to communicate with a socket-io 2.0 server instance, right? Otherwise please let me know :)

**Comment by haruntuncay** [comment]
> that's not a suitable alternative for this lib, right?

No, unfortunately not.

Socket.io is actually a wrapper around web-socket technology. Web-sockets provide the underlying communication mechanisms and socket.io wraps it to ease the usage.
Although you can't use [Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket) as a direct replacement, it does provide some useful mechanisms, where you can very easily have your server-client communicate using websockets, so you might want to check it out :)

**Comment by haruntuncay** [comment]
@Bendor, @DivineThreepwood, @Fi5t, @guftall and everyone, I wanted to announce that I've implemented an independent version of socket.io java client and would be really happy if you guys could use it and give feedback. I would really like to keep it updated and would be happy to receive any feedback/contribution you can give.

**Comment by DivineThreepwood** [comment]
Hey @haruntuncay, thanks for your effort. I will directly switch to your solution on my experimental branch and will give you feedback if my issues still remain.

**Comment by darrachequesne** [comment]
Starting from now, I should be more active on this repository.

Could you please ping me on issues that you would like to see fixed/worked on? Thanks a lot!
